### ISSUE TITLE
./EnvDeploy -l fails

### ISSUE THREAD

**Issue by peteraba** [SynologyOpenSource/pkgscripts-ng#23]
> ./EnvDeploy -l
```
Traceback (most recent call last):
  File "./EnvDeploy", line 335, in <module>
    main(sys.argv[1:])
  File "./EnvDeploy", line 313, in main
    platforms = get_platforms(dsm_ver, build_num, args.platforms)
  File "./EnvDeploy", line 277, in get_platforms
    all_platforms = get_all_platforms(dsm_ver, build_num)
  File "./EnvDeploy", line 256, in get_all_platforms
    pattern = 'AvailablePlatform_%s_%s' % (dsm_ver.split('.')[0], dsm_ver.split('.')[1])
IndexError: list index out of range
```

**Comment by jason1122g** [comment]
can you still reproduce it ?

**Comment by xmstspider** [comment]
You need to use the following format:
``./EnvDeploy -v 7.0 -l``
The EnvDeploy without arguments should show a help instead of typical Python error...

**Comment by pjdubya** [comment]
All I get are errors too, regardless of whether I specify a version of not. This is with both the DSM7.0 and DSM7.2 branches. Is this tool not supported anymore? It's really been >4 years since Synology reviewed open issues? 

$ ./EnvDeploy -v 7.2 -l
Traceback (most recent call last):
  File "C:\Users\peter\source\repos\SynologyToolkit\pkgscripts-ng\EnvDeploy", line 77, in <module>
    main(sys.argv[1:])
  File "C:\Users\peter\source\repos\SynologyToolkit\pkgscripts-ng\EnvDeploy", line 56, in main
    args = parse_args(argv)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\peter\source\repos\SynologyToolkit\pkgscripts-ng\EnvDeploy", line 50, in parse_args
    args.platforms = filter_platforms(args.version, args.platforms)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peter\source\repos\SynologyToolkit\pkgscripts-ng/include/python\pkgdeploy.py", line 304, in filter_platforms
    all_platforms = get_all_platforms(dsm_ver, build_num)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peter\source\repos\SynologyToolkit\pkgscripts-ng/include/python\pkgdeploy.py", line 296, in get_all_platforms
    platforms = BuildEnv.getIncludeVariable(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peter\source\repos\SynologyToolkit\pkgscripts-ng/include/python\BuildEnv.py", line 145, in getIncludeVariable
    return subprocess.check_output(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified


Same error with 

 ./EnvDeploy -v 7.0 -l

or

./EnvDeploy -v 7.2 -l
