### ISSUE TITLE
Cannot create package using Docker container after running it a second time with existing build environment

### ISSUE THREAD

**Issue by raman325** [SynologyOpenSource/pkgscripts-ng#24]
Hi,

I am running `pkgscripts-ng/PkgCreate.py` from a Docker container. In my case, when I first create the container and build the environment to create the package, package creation works as expected. However, when I then try to run it a second time, I can't get the build to run. I posted some of the steps I found failing below, any idea what could be happening?
```
mount: /build_env/ds.avoton-6.2/proc: cannot mount none read-only.
umount: /build_env/ds.avoton-6.2/proc: must be superuser to unmount.
```
```
Traceback (most recent call last):
  File "pkgscripts-ng/PkgCreate.py", line 722, in <module>
    main(sys.argv[1:])
  File "pkgscripts-ng/PkgCreate.py", line 716, in main
    packer.pack_package()
  File "pkgscripts-ng/PkgCreate.py", line 663, in pack_package
    worker.execute()
  File "pkgscripts-ng/PkgCreate.py", line 158, in execute
    self._process_output(self._run(*argv))
  File "pkgscripts-ng/PkgCreate.py", line 290, in _run
    dest_dir = self.package.spk_config.spk_result_dir(self.env_config.suffix)
  File "pkgscripts-ng/PkgCreate.py", line 503, in spk_config
    self.__spk_config = SpkConfig(self.name, self.info, self.settings)
  File "pkgscripts-ng/PkgCreate.py", line 530, in __init__
    self.info = config_parser.KeyValueParser(info)
  File "/pkgscripts-ng/include/python/config_parser.py", line 152, in __init__
    raise ConfigNotFoundError(f)
config_parser.ConfigNotFoundError: /build_env/ds.avoton-6.2/source/WireGuard/INFO
```

`/pkgscripts-ng/SynoBuild: line 129: /dev/fd/62: No such file or directory`
`/pkgscripts-ng/SynoInstall: line 73: /dev/fd/62: No such file or directory`

**Comment by hradec** [comment]
Did you published your docker container somewhere? I'm interested in trying the same to build to my synology DS415play, which is i686 (evansport).

**Comment by hradec** [comment]
> Always:
>/pkgscripts-ng/SynoBuild: line 129: /dev/fd/62: No such file or directory
>/pkgscripts-ng/SynoInstall: line 73: /dev/fd/62: No such file or directory

turns out you have to run the docker container with `--privileged` to fix that issue!

**Comment by raman325** [comment]
not sure how I missed this but I will give that a shot, thanks! I am using this docker container https://github.com/runfalk/synology-wireguard with this script I wrote to make it easy to update wireguard on my NAS: https://github.com/raman325/syno-wg-autoinstaller

EDIT: It's been a while since I have looked at this so I forgot, but I checked and I am running the container with the `privileged` flag so unfortunately that doesn't help me
