### ISSUE TITLE
timeout on timestamp.synoloogy.com

### ISSUE THREAD

**Issue by alucryd** [SynologyOpenSource/pkgscripts-ng#38]
Hi guys, I'm having an issue building a package for DSM 6, see below:

```
PHP Warning:  file_get_contents(http://timestamp.synology.com/timeserver.gpg): failed to open stream: Connection timed out in /pkgscripts/qctrwhyysrj on line 2
```

Is the server down or is it a problem on my end? Tried this address from several servers and it seems unresponsive.

**Comment by SynologyOpenSource** [comment]
Is this problem still happened? 
We check server connection now is back to normal.

**Comment by alucryd** [comment]
Still an issue via IPv6:
```
PHP Warning:  file_get_contents(http://timestamp.synology.com/timeserver.gpg): failed to open stream: Connection timed out in /pkgscripts/oceqojvdghn on line 2
Can't read timeserver.gpg
Make token failed.
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[alpine] Sign package:  php /pkgscripts-ng/CodeSign.php --sign=/image/packages/EmbyServer-alpine-4.7.0.11-0001_debug.spk
Traceback (most recent call last):
  File "/home/embybuilder/Buildbot/synology/pkgscripts/PkgCreate.py", line 279, in _code_sign
    check_call(cmd, shell=True, executable="/bin/bash")
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' php /pkgscripts-ng/CodeSign.php --sign=/image/packages/EmbyServer-alpine-4.7.0.11-0001_debug.spk' returned non-zero exit status 1.
```
Looks fine via IPv4 though, I'll cheat with /etc/hosts in the meantime.

**Comment by SynologyOpenSource** [comment]
We haven't supported IPv6 for now and there are some reasons:
1. IPv6 adoption rate is still not high
2. Most of IPv6 translates back to IPv4, sometimes it may cause strange issue
3. Everyone has IPv4
