### ISSUE TITLE
Development environment for DSM7.0 won't install

### ISSUE THREAD

**Issue by tallinn1960** [SynologyOpenSource/pkgscripts-ng#40]
Trying to setup a development environment as described in

https://help.synology.com/developer-guide/getting_started/prepare_environment.html

# apt-get install cifs-utils python python-pip python3 python3-pip

Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Hinweis: »python-is-python2« wird an Stelle von »python« gewählt.
Paket python-pip ist nicht verfügbar, wird aber von einem anderen Paket
referenziert. Das kann heißen, dass das Paket fehlt, dass es abgelöst
wurde oder nur aus einer anderen Quelle verfügbar ist.
Doch die folgenden Pakete ersetzen es:
  python3-pip

E: Für Paket »python-pip« existiert kein Installationskandidat.

# cd pkgscripts-ng/
# git checkout DSM7.0
# ./EnvDeploy -v 7.0 -p avoton 
chroot: der Befehl „ln“ konnte nicht ausgeführt werden: Fehler im Format der Programmdatei
Traceback (most recent call last):
  File "/toolkit/pkgscripts-ng/include/python/exec_env.py", line 76, in execute
    output = commandrunner.run(cmd, display=display, **kwargs)
  File "/toolkit/pkgscripts-ng/include/python/commandrunner.py", line 39, in run
    raise RunShellFailed(p.returncode, cmd, output)
commandrunner.RunShellFailed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/toolkit/pkgscripts-ng/./EnvDeploy", line 77, in <module>
    main(sys.argv[1:])
  File "/toolkit/pkgscripts-ng/./EnvDeploy", line 71, in main
    toolkit.deploy()
  File "/toolkit/pkgscripts-ng/include/python/pkgdeploy.py", line 207, in deploy
    self.link_pkgscripts(envs[platform])
  File "/toolkit/pkgscripts-ng/include/python/pkgdeploy.py", line 166, in link_pkgscripts
    env.link('pkgscripts-ng', 'pkgscripts')
  File "/toolkit/pkgscripts-ng/include/python/exec_env.py", line 61, in link
    self.execute(['ln', '-sf', src, dest])
  File "/toolkit/pkgscripts-ng/include/python/exec_env.py", line 79, in execute
    raise EnvError(
exec_env.EnvError: ('Execute chroot /toolkit/build_env/ds.avoton-7.0 ln -sf pkgscripts-ng pkgscripts failed', 'chroot: der Befehl „ln“ konnte nicht ausgeführt werden: Fehler im Format der Programmdatei')

Full stop.

This is an an Ubuntu 21.-10 system.

Please note that using python for anything will grant to give you errors like this.

**Comment by danblae** [comment]
Hey, I had a similar problem and the issue is the include/toolkit.config file. Just add a line like this: 
```
AvailablePlatform_7_0="avoton"
```
I already checked on https://sourceforge.net/projects/dsgpl/files/toolkit/DSM7.0/ if this actually exists and it does.

I would make a pull request, but I barely have any time at the moment and pull requests don't seem to be accepted for the past year.
(This is not a guarantee that it will work, but it might.)
(And maybe make sure your error messages are in English. This way you will be able to find help much quicker online.)
