### ISSUE TITLE
Error trying to install on DSM-7.2 (platform Geminilake)

### ISSUE THREAD

**Issue by rabdalov** [SynologyOpenSource/pkgscripts-ng#45]
[2023-06-19 11:21:31,626] INFO: tar -xhf /toolkit/toolkit_tarballs/ds.geminilake-
7.2.dev.txz -C /toolkit/build_env/ds.geminilake-7.2                              
mount: /toolkit/build_env/ds.geminilake-7.2/proc: cannot mount none read-only.   
Traceback (most recent call last):                                               
  File "/toolkit/pkgscripts-ng/./EnvDeploy", line 77, in <module>                
    main(sys.argv[1:])                                                           
  File "/toolkit/pkgscripts-ng/./EnvDeploy", line 71, in main                    
    toolkit.deploy()                                                             
  File "/toolkit/pkgscripts-ng/include/python/pkgdeploy.py", line 207, in deploy 
    self.link_pkgscripts(envs[platform])                                         
  File "/toolkit/pkgscripts-ng/include/python/pkgdeploy.py", line 166, in link_pk
gscripts                                                                         
    env.link('pkgscripts-ng', 'pkgscripts')                                      
  File "/toolkit/pkgscripts-ng/include/python/exec_env.py", line 61, in link     
    self.execute(['ln', '-sf', src, dest])                                       
  File "/toolkit/pkgscripts-ng/include/python/exec_env.py", line 68, in execute  
    subprocess.check_call(['mount', '-t', 'proc', 'none', mount_point])          
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call              
    raise CalledProcessError(retcode, cmd)                                       
subprocess.CalledProcessError: Command '['mount', '-t', 'proc', 'none', '/toolkit
/build_env/ds.geminilake-7.2/proc']' returned non-zero exit status 32.

**Comment by HBrendy** [comment]
Yep, I can confirm: same version, same platform, same error.

**Comment by SynologyOpenSource** [comment]
Have you tried other platforms to see if the same error message occurs?
What is the error output when you run the command 'mount -t proc none /toolkit/build_env/ds.geminilake-7.2/proc' directly?"

**Comment by jcarnat** [comment]
Same thing happens here with a different platform:
```
# mount -t proc none /toolkit/build_env/ds.apollolake-7.2/proc
mount: /toolkit/build_env/ds.apollolake-7.2/proc: cannot mount none read-only.
```

If I run:
```
# docker create -it --name synodev --privileged --security-opt systempaths=unconfined ubuntu:latest
```
the error message disappear.

**Comment by pjdubya** [comment]
I had this error but I found that it went away when I deleted a different platform install, i.e. whatever else may have been at /toolkit/build_env/*

And/or it was when I updated my docker container to have elevated permissions.
