### ISSUE TITLE
PkgCreate.py fails with an error on a basic example

### ISSUE THREAD

**Issue by dmakarov** [SynologyOpenSource/pkgscripts-ng#8]
Following instructions in Synology DSM6.0 Developer Guide and trying to compile the minimalPkg as stated in the guide result in the following error

`/toolkit# ./pkgscripts/PkgCreate.py -p armada38x -v 6.1 -x 0 minimalPkg`

```
============================================================
                Start to run "Link Project"                 
------------------------------------------------------------
Traceback (most recent call last):
  File "./pkgscripts/PkgCreate.py", line 722, in <module>
    main(sys.argv[1:])
  File "./pkgscripts/PkgCreate.py", line 716, in main
    packer.pack_package()
  File "./pkgscripts/PkgCreate.py", line 663, in pack_package
    worker.execute()
  File "./pkgscripts/PkgCreate.py", line 158, in execute
    self._process_output(self._run(*argv))
  File "./pkgscripts/PkgCreate.py", line 195, in _run
    worker.execute(version, update_hook, depends_cache)
  File "./pkgscripts/PkgCreate.py", line 158, in execute
    self._process_output(self._run(*argv))
  File "./pkgscripts/PkgCreate.py", line 241, in _run
    link_scripts(chroot)
  File "/toolkit/pkgscripts/include/python/link_project.py", line 33, in link_scripts
    shutil.rmtree(dest_path)
  File "/usr/lib/python3.5/shutil.py", line 484, in rmtree
    onerror(os.path.islink, path, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 482, in rmtree
    raise OSError("Cannot call rmtree on a symbolic link")
OSError: Cannot call rmtree on a symbolic link
```

**Comment by dmakarov** [comment]
The problem is that when `./EnvDeploy -v 6.1 -p armada38x` finished running, there's a symbolic link in `/toolkit/build_env/ds.armada38x-6.1`
```
lrwxrwxrwx   1 root root     13 jul 15 18:47 pkgscripts -> pkgscripts-ng
```
Instead, it should be
```
lrwxrwxrwx   1 root root     13 jul 15 18:47 pkgscripts-ng -> pkgscripts
```
